steps:
  - name: gradle:6.3-jdk8
    entrypoint: gradle
    args: ['build']
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/test/api-test:${_VERSION}','.']
  - name: gcr.io/cloud-builders/docker
    args: ['push', 'gcr.io/$PROJECT_ID/test/api-test:${_VERSION}']
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=k8s/deployment.yaml
      - --image=gcr.io/$PROJECT_ID/test/api-test:${_VERSION}
      - --location=${_CLOUDSDK_COMPUTE_ZONE}
      - --cluster=${_CLOUDSDK_CONTAINER_CLUSTER}