apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-build-test
  labels:
    app: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: gcr.io/cacos-stg/test/api-test:5
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-build-test-service
spec:
  type: NodePort
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

